name: totc
description: A sample web application
dependencies:
  browser: any
  hangouts_api: any
  mime: any
  polymer: any
  route: any
  stagexl: any
transformers:
- polymer:
    entry_points: web/index.html
